### ISSUE TITLE
stage I

### ISSUE THREAD

**Issue by rusdevops** [ovan-iu8/HW_Explorer_01#1]
- [x] 1. Отсутсвует проверка состояния стандартного потока ввода 
https://github.com/ovan-iu8/HW_Explorer_01/blob/9c6ddac1ed2bc87203873768eef055becbf3b2b9/main.cpp#L18
 - [x] 2. Не все файлы имеют расширение **.dat**
https://github.com/ovan-iu8/HW_Explorer_01/blob/9c6ddac1ed2bc87203873768eef055becbf3b2b9/main.cpp#L21
- [x] 3. Отсутсвует проверка существования файла
https://github.com/ovan-iu8/HW_Explorer_01/blob/9c6ddac1ed2bc87203873768eef055becbf3b2b9/main.cpp#L26
- [x] 4. Присутсвует логическая ошибка https://github.com/ovan-iu8/HW_Explorer_01/blob/9c6ddac1ed2bc87203873768eef055becbf3b2b9/main.cpp#L32

**Comment by ovan-iu8** [comment]
Пункты 1 и 3: Добавил проверку на существование файла по введенному адресу. Так как возникли сложности с проверкой данных введенных в string (string - съедает и цифры, и буквы, и символы).

Пункт 2: Убрал добавление к адресу строки ".dat" Теперь необходимо вводить путь к файлу с его форматом.

Пункт 4: Делю значение на 1000, так как fs::file_size возвращает значение в байтах.
